spring.application.name : First
server:
  port: 8989

spring:
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        show-sql: true
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TeamDB
    username: Team
    password: improvement


  sql:
    init:
      encoding: UTF-8

  mail:
    host: smtp.gmail.com
    port: 587
    username: ibrohimovzuhriddin310@gmail.com
    password: gxzblhgjnaydmysn

    properties:
      mail:
        smtp:
          #          ssl:
          #            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          required: true
token:
    signing:
      key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855